### PR TITLE
Community Showcase: add Epic Rap Battles of Bluesky

### PR DESCRIPTION
**Pull request by jlowin**
This is a fun app that uses the API to pull public profiles + histories and uses them to seed the personalities and topics of two AI rappers.

www.battlesky.ai

### Edit

I'm going to close this because what was intended to be a silly app built on the public API became an external flashpoint for misinformation, which is disappointing. As the app itself indicates, it uses exclusively public data and neither stores that data nor uses it to train an LLM. It does not crawl Bluesky proactively, nor does it use the firehose. It is less invasive than a Bluesky client that allows you to bookmark posts. It is less invasive than a search engine. 

I understand that "AI", or perhaps a misunderstanding thereof, is the trigger here, but Bluesky (and more importantly the underlying protocol) is a public network. That's the entire appeal of it. I don't agree with the merit of the opinions expressed here, but their authors are welcome to hold them.

### CODE REVIEW

**Comment by furioursus** [comment]
Yo, Bsky is a really nice community we have. It really sucks that you built something that feeds our words into a machine with no mechanisms for opting out.

**Comment by BenCHamlin** [comment]
Feels like this was made without any consideration for anybody’s consent. Generative AI is a resource waste in a lot of people’s eyes and users don’t consent to their personal material being remixed like this without their knowledge

**Comment by moonlitsara** [comment]
this is very not cool. the vast majority of people i interact with (including myself) do not consent to have our data generated into your app. if you're going to insist on polluting the atmosphere with this, it should be opt-in only with a means of verifying users' consent (app password, liking a specific post or following a specific on-site account, etc.)

**Comment by moonlitsara** [comment]
this is very not cool. the vast majority of people i interact with (including myself) do not consent to have our data used by your app. if you're going to insist on polluting the atmosphere with this, it should be opt-in only with a means of verifying users' consent (app password, liking a specific post or following a specific on-site account, etc.)

**Pull request closed without merging**
