### PR TITLE
Add rust sdk to homepage

### PR DESCRIPTION
**Pull request by sugyan**
It would be great if you could also list the Rust SDK that I maintain. I'll also provide code snippets for tutorials if you want.

### CODE REVIEW

**Comment by emilyliu7321** [comment]
Hi @sugyan! How stable is this SDK? We want to keep the ones listed on the homepage to just a select few for now

**Comment by sugyan** [comment]
"How stable"... What level of stability is expected?

Some features are still under development, but at present it is possible to automatically generate type definitions and methods from lexicon schema and process XRPC requests.

**Comment by emilyliu7321** [comment]
In that case I'll mark it as a favorite for the community showcase for now, and hope to add yours and others to the homepage in the future!

**Comment by emilyliu7321** [comment]
Added to favorites in this commit: https://github.com/bluesky-social/bsky-docs/commit/5625a8e0d269cb3adc8dfd7faa4f9ac48930eb60

**Pull request closed without merging**
